"""fixed add of membership and clearland phase table

Revision ID: 027cad371351
Revises: 30fcf79e5c95
Create Date: 2026-02-13 01:18:01.486372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '027cad371351'
down_revision: Union[str, Sequence[str], None] = '30fcf79e5c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clearland_phases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_participant_id', sa.String(length=128), nullable=False),
    sa.Column('notes_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'phase', 'effective_from', name='uq_clearland_phase_project_phase_from')
    )
    op.create_index('ix_clearland_phase_project_active', 'clearland_phases', ['project_id', 'effective_to'], unique=False)
    op.create_index(op.f('ix_clearland_phases_phase'), 'clearland_phases', ['phase'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clearland_phases_phase'), table_name='clearland_phases')
    op.drop_index('ix_clearland_phase_project_active', table_name='clearland_phases')
    op.drop_table('clearland_phases')
    # ### end Alembic commands ###
