"""add participant and project  table

Revision ID: 1955168c8cb4
Revises: 097fa12f5687
Create Date: 2026-01-08 22:58:47.696198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1955168c8cb4'
down_revision: Union[str, Sequence[str], None] = '097fa12f5687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow', 'username', name='uq_participant_workflow_username')
    )
    op.create_index('ix_participants_workflow_role', 'participants', ['workflow', 'role'], unique=False)
    op.create_table('participant_auth',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username', name='uq_participant_auth_username')
    )
    op.drop_table('saleable_project_members')
    op.drop_table('saleable_developer_asks')
    op.drop_table('roles')
    op.drop_table('user_roles')
    op.drop_table('saleable_owner_asks')
    op.drop_table('saleable_projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saleable_projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('property_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('owner_entity_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('address_line', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('zone', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('plot_area_sqm', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('existing_builtup_sqm', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('redevelopment_intent_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('consent_state', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('consent_captured_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('bidding_round_t0', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bidding_window_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('bidding_window_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.TEXT(), server_default=sa.text("'Asia/Kolkata'::text"), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'DRAFT'::text"), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('metadata_locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owning_org_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("consent_state = ANY (ARRAY['DRAFT'::text, 'CONSENTED'::text, 'WITHDRAWN'::text])", name='saleable_projects_consent_state_check'),
    sa.CheckConstraint("property_type = ANY (ARRAY['cooperative_society'::text, 'private_owner'::text])", name='saleable_projects_property_type_check'),
    sa.CheckConstraint("status = ANY (ARRAY['DRAFT'::text, 'PUBLISHED'::text, 'ARCHIVED'::text])", name='saleable_projects_status_check'),
    sa.CheckConstraint('bidding_round_t0 >= 0', name='saleable_projects_bidding_round_t0_check'),
    sa.CheckConstraint('existing_builtup_sqm >= 0::numeric', name='saleable_projects_existing_builtup_sqm_check'),
    sa.CheckConstraint('plot_area_sqm >= 0::numeric', name='saleable_projects_plot_area_sqm_check'),
    sa.PrimaryKeyConstraint('id', name='saleable_projects_pkey'),
    sa.UniqueConstraint('project_id', name='saleable_projects_project_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('saleable_owner_asks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reserve_price', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('relocation_terms', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('min_carpet_area', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['saleable_projects.id'], name=op.f('saleable_owner_asks_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('saleable_owner_asks_pkey'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('user_roles_pkey'))
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey')),
    sa.UniqueConstraint('code', name=op.f('roles_code_key'))
    )
    op.create_table('saleable_developer_asks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ask_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('min_fsi', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('expected_revenue', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['saleable_projects.id'], name=op.f('saleable_developer_asks_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('saleable_developer_asks_pkey'))
    )
    op.create_table('saleable_project_members',
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("role = ANY (ARRAY['OWNER'::text, 'DEVELOPER'::text, 'VIEWER'::text])", name=op.f('saleable_project_members_role_check')),
    sa.ForeignKeyConstraint(['project_id'], ['saleable_projects.id'], name=op.f('saleable_project_members_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id', name=op.f('saleable_project_members_pkey'))
    )
    op.drop_table('participant_auth')
    op.drop_index('ix_participants_workflow_role', table_name='participants')
    op.drop_table('participants')
    # ### end Alembic commands ###
