"""fix unit_inventory relationships

Revision ID: 24c314469670
Revises: 68fc43253b75
Create Date: 2026-02-04 18:48:47.689181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c314469670'
down_revision: Union[str, Sequence[str], None] = '68fc43253b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit_inventories', sa.Column('workflow', sa.String(length=32), nullable=False))
    op.add_column('unit_inventories', sa.Column('project_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_unit_inventory_round'), table_name='unit_inventories')
    op.create_index('ix_unit_inventory_scope', 'unit_inventories', ['workflow', 'project_id', 'round_id'], unique=False)
    op.create_foreign_key(None, 'unit_inventories', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit_inventories', type_='foreignkey')
    op.drop_index('ix_unit_inventory_scope', table_name='unit_inventories')
    op.create_index(op.f('ix_unit_inventory_round'), 'unit_inventories', ['round_id'], unique=False)
    op.drop_column('unit_inventories', 'project_id')
    op.drop_column('unit_inventories', 'workflow')
    # ### end Alembic commands ###
