"""add unit inventory table

Revision ID: 68fc43253b75
Revises: 1ba313f548dc
Create Date: 2026-02-04 18:29:24.018143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68fc43253b75'
down_revision: Union[str, Sequence[str], None] = '1ba313f548dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_inventories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('lu', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('tdru', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('pru', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('dcu', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dcu IS NULL OR dcu >= 0', name='ck_unit_inventory_dcu_nonneg'),
    sa.CheckConstraint('lu IS NULL OR lu >= 0', name='ck_unit_inventory_lu_nonneg'),
    sa.CheckConstraint('pru IS NULL OR pru >= 0', name='ck_unit_inventory_pru_nonneg'),
    sa.CheckConstraint('tdru IS NULL OR tdru >= 0', name='ck_unit_inventory_tdru_nonneg'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id'),
    sa.UniqueConstraint('round_id', name='uq_unit_inventory_round')
    )
    op.create_index('ix_unit_inventory_round', 'unit_inventories', ['round_id'], unique=False)
    op.drop_index(op.f('ix_subsidized_model_proj'), table_name='subsidized_economic_models')
    op.drop_table('subsidized_economic_models')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subsidized_economic_models',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_published_version', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('lu_total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lu_open_space', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pru_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tdru_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dcu_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pvic', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('alpha', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('beta', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('gamma', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('ec', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('gci', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('gce', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('gcu', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('subsidized_economic_models_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('subsidized_economic_models_pkey')),
    sa.UniqueConstraint('project_id', 'version', name=op.f('uq_subsidized_model_proj_ver'))
    )
    op.create_index(op.f('ix_subsidized_model_proj'), 'subsidized_economic_models', ['project_id'], unique=False)
    op.drop_index('ix_unit_inventory_round', table_name='unit_inventories')
    op.drop_table('unit_inventories')
    # ### end Alembic commands ###
