"""create slum consent and document tables

Revision ID: 7e695d4aa2c5
Revises: 53e8e84312de
Create Date: 2026-01-29 14:11:30.627404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e695d4aa2c5'
down_revision: Union[str, Sequence[str], None] = '53e8e84312de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slum_consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.String(length=64), nullable=False),
    sa.Column('portal_type', sa.String(length=32), nullable=False),
    sa.Column('consent_text', sa.String(), nullable=False),
    sa.Column('agreed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slum_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.String(length=64), nullable=False),
    sa.Column('portal_type', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slum_documents')
    op.drop_table('slum_consents')
    # ### end Alembic commands ###
