"""add clearland_project_membership table

Revision ID: f9488f58442a
Revises: 8ab0915e196c
Create Date: 2026-02-13 00:50:00.329542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9488f58442a'
down_revision: Union[str, Sequence[str], None] = '8ab0915e196c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clearland_phase_project_active'), table_name='clearland_phases')
    op.drop_table('clearland_phases')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clearland_phases',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('phase', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('effective_from', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('effective_to', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by_participant_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('notes_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('clearland_phases_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('clearland_phases_pkey')),
    sa.UniqueConstraint('project_id', 'phase', 'effective_from', name=op.f('uq_clearland_phase_project_phase_from'))
    )
    op.create_index(op.f('ix_clearland_phase_project_active'), 'clearland_phases', ['project_id', 'effective_to'], unique=False)
    # ### end Alembic commands ###
